name: 02 - jobs outputs

on:
    workflow_dispatch:

jobs:
    deploy-job:
        runs-on: ubuntu-latest
        outputs:
            deployment_url: ${{ steps.deploy.outputs.deployment_url }}
        steps:
            - name: Deploy application
              id: deploy
              run: |
                echo "Deploying application..."
                sleep 3
                echo "deployment_url=https://www.mj.com" >> $GITHUB_OUTPUT
        
    notification-job:
        runs-on: ubuntu-latest
        needs: 
            - deploy-job
        steps:
            - name: send-notification
              run: |
                echo "Sending notification..."
                echo "Application deployed at ${{ needs.deploy-job.outputs.deployment_url }}"
                echo "Notification sent successfully...."